// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAvxdScjQbOCI3LaXGDSglUtY6Ji0S74',
    appId: '1:1005294821666:web:7e76f6d363dc87c078857b',
    messagingSenderId: '1005294821666',
    projectId: 'socialmedialogin-964d8',
    authDomain: 'socialmedialogin-964d8.firebaseapp.com',
    storageBucket: 'socialmedialogin-964d8.firebasestorage.app',
    measurementId: 'G-VLB5Q8KCC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22mM2s4YO22NJEYLBCaPDLx0UXj6oZhU',
    appId: '1:1005294821666:android:2c2a73b6d355ae7878857b',
    messagingSenderId: '1005294821666',
    projectId: 'socialmedialogin-964d8',
    storageBucket: 'socialmedialogin-964d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkcSZkKjacbyX1JKcU6JX_vknFcv6z0Q',
    appId: '1:1005294821666:ios:c3c42a56675000db78857b',
    messagingSenderId: '1005294821666',
    projectId: 'socialmedialogin-964d8',
    storageBucket: 'socialmedialogin-964d8.firebasestorage.app',
    iosClientId: '1005294821666-qnu6dguj7dmoj1vi0ok8thqvsoqmvbiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmedialogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkcSZkKjacbyX1JKcU6JX_vknFcv6z0Q',
    appId: '1:1005294821666:ios:c3c42a56675000db78857b',
    messagingSenderId: '1005294821666',
    projectId: 'socialmedialogin-964d8',
    storageBucket: 'socialmedialogin-964d8.firebasestorage.app',
    iosClientId: '1005294821666-qnu6dguj7dmoj1vi0ok8thqvsoqmvbiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmedialogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQAvxdScjQbOCI3LaXGDSglUtY6Ji0S74',
    appId: '1:1005294821666:web:c38fb3c0972b014a78857b',
    messagingSenderId: '1005294821666',
    projectId: 'socialmedialogin-964d8',
    authDomain: 'socialmedialogin-964d8.firebaseapp.com',
    storageBucket: 'socialmedialogin-964d8.firebasestorage.app',
    measurementId: 'G-870DDRMKSG',
  );
}
